apiVersion: v1
kind: Secret
metadata:
  name: manyfold-secrets
  labels:
    app.kubernetes.io/name: manyfold
type: Opaque
stringData:
  SECRET_KEY_BASE: local-development-only-manyfold-secret-key-change-me
