apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manyfold-library
  labels:
    app.kubernetes.io/name: manyfold
    app.kubernetes.io/component: model-library
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
