apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: manyfold-secrets
  labels:
    app.kubernetes.io/name: manyfold
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: manyfold-secrets
    creationPolicy: Owner
    template:
      data:
        SECRET_KEY_BASE: "{{ .secretKeyBase }}"
  data:
    - secretKey: secretKeyBase
      remoteRef:
        key: openscad
        property: manyfold-secret-key-base
