apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openscad

resources:
  - ../../base
  - external-secret.yaml
  - model-library-storage.yaml
  - postgres-cluster.yaml
  - objectstore.yaml
  - scheduledbackup.yaml
  - dragonfly.yaml
  - ingressroute.yaml

patches:
  - path: oidc-config.yaml
